spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/smart_campus_db}
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
