// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9EOeExOpGV5z0R7-yUq9pS7PUg1iuws8',
    appId: '1:847860256580:web:9a31b382c96fce0c569111',
    messagingSenderId: '847860256580',
    projectId: 'gnits-smart-campus',
    authDomain: 'gnits-smart-campus.firebaseapp.com',
    storageBucket: 'gnits-smart-campus.firebasestorage.app',
    measurementId: 'G-ZKH5CVDWWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV8Qbp-Cngn_N3f5pT1rFLbDI2WHlMtno',
    appId: '1:847860256580:android:f6eba7c8c63d90c9569111',
    messagingSenderId: '847860256580',
    projectId: 'gnits-smart-campus',
    storageBucket: 'gnits-smart-campus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE-HN4UMe40EfKV_ajjvoTgOAwKuF51SU',
    appId: '1:847860256580:ios:adcdab44d9d3a2df569111',
    messagingSenderId: '847860256580',
    projectId: 'gnits-smart-campus',
    storageBucket: 'gnits-smart-campus.firebasestorage.app',
    iosBundleId: 'com.example.smartCampusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE-HN4UMe40EfKV_ajjvoTgOAwKuF51SU',
    appId: '1:847860256580:ios:adcdab44d9d3a2df569111',
    messagingSenderId: '847860256580',
    projectId: 'gnits-smart-campus',
    storageBucket: 'gnits-smart-campus.firebasestorage.app',
    iosBundleId: 'com.example.smartCampusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9EOeExOpGV5z0R7-yUq9pS7PUg1iuws8',
    appId: '1:847860256580:web:3ccf712411c09162569111',
    messagingSenderId: '847860256580',
    projectId: 'gnits-smart-campus',
    authDomain: 'gnits-smart-campus.firebaseapp.com',
    storageBucket: 'gnits-smart-campus.firebasestorage.app',
    measurementId: 'G-7TMPMKR9K0',
  );
}
