# FROM eclipse-temurin:17-jre
# WORKDIR /app
# COPY target/smartcampusbackend-0.0.1-SNAPSHOT.jar app.jar
# EXPOSE 8080
# ENTRYPOINT ["java","-jar","app.jar"]


FROM maven:3.9-eclipse-temurin-17 AS build

WORKDIR /app

COPY pom.xml .
COPY .mvn .mvn

RUN mvn -B -DskipTests dependency:go-offline

COPY src src

RUN mvn -B -DskipTests package


FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=build /app/target/smartcampusbackend-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]